# appspec.yml
# code deploy

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/spring-cicd/ # 프로젝트 이름
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user


hooks:

  AfterInstall:
    - location: scripts/step1.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/step2.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/step3.sh
      timeout: 60
      runas: root
